plugins {
    id 'java'
    id 'application'
    id 'com.google.protobuf' version '0.9.4'
}

repositories { mavenCentral() }

java {
    toolchain { languageVersion = JavaLanguageVersion.of(17) }
}
application {
     mainClass = (project.findProperty("mainClass") ?: "EchoServer") as String
}

sourceSets {
    main {
        java {
            srcDirs = [
                'G-RPC/src/main/java',
                'build/generated/source/proto/main/java',
                'build/generated/source/proto/main/grpc'
            ]
        }
        proto {
            srcDirs = ['G-RPC/src/main/proto']
        }
        resources.srcDirs = ['G-RPC/src/main/resources']
    }
}

dependencies {
    implementation 'io.grpc:grpc-netty-shaded:1.66.0'
    implementation 'io.grpc:grpc-protobuf:1.66.0'
    implementation 'io.grpc:grpc-stub:1.66.0'
    implementation 'com.google.protobuf:protobuf-java:3.25.3'
    compileOnly  'org.apache.tomcat:annotations-api:6.0.53'
    testImplementation 'junit:junit:4.13.2'
}

protobuf {
    protoc { artifact = 'com.google.protobuf:protoc:3.25.3' }
    plugins { grpc { artifact = 'io.grpc:protoc-gen-grpc-java:1.66.0' } }
    generateProtoTasks {
        all().configureEach { task -> task.plugins { grpc {} } }
    }
}

tasks.named('compileJava') { dependsOn(tasks.named('generateProto')) }

tasks.withType(JavaExec).configureEach {
    // lets EchoClient read from Scanner(System.in), etc.
    standardInput = System.in
}
